version: "3.5"
services:
  app:
    restart: always
    container_name: hangar-case
    build: ./
    ports:
      - 82:80
    volumes:
      - ./app:/home/app
    networks:
      - app_network
networks:
  app_network:
    driver: bridge